name: Run TestNG Tests

on:
  push:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      suite:
        description: 'TestNG suite to run (e.g., testng, smoke-suite, regression-suite)'
        required: false
        default: 'testng'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run TestNG suite
        run: |
          echo "Running suite: ${{ github.event.inputs.suite }}"
          mvn test -Dsuite=${{ github.event.inputs.suite }}

      - name: Archive TestNG reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: testng-reports
          path: target/surefire-reports/
